

- name: Install NodeJs
  ansible.builtin.shell: dnf module disable nodejs -y; dnf module enable nodejs:20 -y 

- name: Install nodeJs 
  ansible.builtin.dnf: 
    name: nodejs 
    state: installed

- name: Copy docker repo
  ansible.builtin.copy: 
    src: docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo

- name: Install docker 
  ansible.builtin.dnf: 
    name:  docker 
    state: latest

- name: Add Docker group to Jenkins 
  ansible.builtin.user: 
    name: jenkins 
    groups: docker 
    append: yes

- name: start docker service 
  ansible.builtin.systemd_service: 
    name: docker 
    state: restarted
    enabled: yes 