- name: Download vault repo file
  ansible.builtin.get_urrl:
    url: https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
    dest: /etc/yum.repos.d/hashicorp.repo

- name: Intsall vault
  ansible.builtin.dnf:
    name: vault
    state: latest

- name: start avult service
  ansible.builtin.systemd_service:
    name: vault
    state: restarted
    enabled: yes
