name: Provison tool infra vault
run-name: ${{ github.actor }} - ${{ github.event.head_commit.message }}
on: [workflow_dispatch] # list
jobs:
  Provison: #infra tool environment
    runs-on: self-hosted
    steps:
         - uses: actions/checkout@v4 # get the code
         - name: Run vault
           run: ansible-playbook -i {{secrets.RUNNER_SERVER}}, tool-setup.yml -e ansible_user=${{secrets.SSH_USER_NAME}} -e ansible_password=${{secrets.SSH_PASSWORD}}  -e tool_name=github-runner
         - name:  complete
           run: echo complete