name: Provison tool infra
run-name: ${{ github.actor }} - ${{ github.event.head_commit.message }}
on: [push,workflow_dispatch] # list
jobs:
  Provison: #infra tool environment
    runs-on: ubuntu-latest
    steps:
         - uses: actions/checkout@v4 # get the code
         - run: terraform init

  