name: Provison tool infra vault
run-name: ${{ github.actor }} - ${{ github.event.head_commit.message }}
on: [workflow_dispatch] # list
jobs:
  Provison: #infra tool environment
    runs-on: self-hosted
    steps:
         - uses: actions/checkout@v4 # get the code
         - name: Run vault
           run: ansible-playbook -i vault-internal.example.online, tool-setup.yml -e ansible_user=${{github-action secret}} -e ansible_password=${{github action secret}}  -e tool_name=vault
         - name:  complete
           run: echo complete